language: bash
before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - sudo apt install imagemagick
    - sudo apt install ghostscript
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x web_log.tsv.7z
script:
  - cd ch0x04
  - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/worldcupplayerinfo.tsv"
  - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/web_log.tsv.7z"
  - 7z x -ot web_log.tsv.7z
  - mv t/web_log.tsv web_log.tsv
  - ls -l
  - bash chap0x04/task1.sh -h
  - bash chap0x04/task1.sh -i chap0x04/test/ -q 50% -r 90 -w cuc -p prefix -s suffix -c
  - bash chap0x04/task2.sh -h
  - bash chap0x04/task2.sh -ar -p -ac -n
  - bash chap0x04/task3.sh -h
  - bash chap0x04/task3.sh -o
  - bash chap0x04/task3.sh -i
  - bash chap0x04/task3.sh -u
  - bash chap0x04/task3.sh -s
  - bash chap0x04/task3.sh -u4
  - bash chap0x04/task3.sh -uh /images/NASA-logosmall.gif
  
after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck chap0x04/*.sh
  
after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
